name: Figma Plugin CI

on:
  push:
    # Run against main branch only.
    branches: [main]
  pull_request:
    # Include events emitted on code change only.
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
          yarn test
        env:
          CI: true
